#!/bin/bash
args=(
-M q35,accel=kvm
-smp 2
-m 4G
-cpu host,kvm=off

-acpitable file=fakedev.aml
-device isa-debugcon,iobase=0x404,chardev=dbug
-chardev file,id=dbug,path=/dev/stdout

-device isa-debugcon,iobase=0x403,chardev=dbugfw
-chardev file,id=dbugfw,path=/dev/stdout

-smbios type=0,date=01/01/2018
-device ioh3420,id=rp1,bus=pcie.0,addr=1c.0,port=1
-device vfio-pci,bus=rp1,host=01:00.0,rombar=0,x-pci-sub-vendor-id=0x1028,x-pci-sub-device-id=0x07be
-fw_cfg name=opt/nl.lekensteyn/vfio-vbios,file=vbios.rom
#-vga none

-netdev user,id=net0
-device e1000,netdev=net0

# For easier offline file sharing
-device nec-usb-xhci

-vnc :0

-trace vfio_pci_read_config,file=/dev/stdout
-trace vfio_pci_write_config,file=/dev/stdout

# Patched to trace hw/pci-bridge/pcie_root_port.c
-trace rp_read_config,file=/dev/stdout
-trace rp_write_config,file=/dev/stdout

"$@"
)
case "$*" in
*-cdrom*|*-drive*|*.qcow2*) ;;
*)
    args+=(
        -cdrom archlinux-2018.07.01-x86_64.iso
        #-drive file=w10.qcow2,format=qcow2
    )
    ;;
esac


echo qemu-system-x86_64 "${args[@]}"
qemu-system-x86_64 "${args[@]}"
